<?php

namespace RayanLevert\Model\Tests\Model;

use PDO;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use RayanLevert\Model\Attributes\AutoIncrement;
use RayanLevert\Model\Attributes\Column;
use RayanLevert\Model\Attributes\PrimaryKey;
use RayanLevert\Model\Attributes\Validation\Required;
use RayanLevert\Model\Columns\Type;
use RayanLevert\Model\Connections\Mysql;
use RayanLevert\Model\DataObject;
use RayanLevert\Model\Model;
use RayanLevert\Model\Queries\Mysql as QueriesMysql;
use RayanLevert\Model\State;

/**
 * This class is used to test with a **real** MySQL database all the queries generated by the Model class
 *
 * Assuring the database *model* is created and table *user* as well
 *
 * - id INT AUTO_INCREMENT PRIMARY KEY
 * - last_name VARCHAR(45) NOT NULL
 * - first_name VARCHAR(45) NOT NULL
 */
class MysqlTest extends TestCase
{
    private DataObject $dataObject;

    protected function setUp(): void
    {
        $this->dataObject = new DataObject($this->getConnectionClass(), new QueriesMysql());
        $this->dataObject->startTransaction();

        Model::$dataObject = $this->dataObject;
    }

    protected function tearDown(): void
    {
        $this->dataObject->rollback();

        Model::$dataObject = null;
    }

    #[Test]
    public function createSaveAndDeleteSuccessfully(): void
    {
        $model = new User();

        $model->firstName = 'John';
        $model->lastName  = 'Doe';

        $this->assertSame(State::TRANSIANT, $model->state);

        // No exception thrown
        $model->create();
        $id = $model->id;

        $this->assertSame(State::PERSISTENT, $model->state);

        // The AutoIncrement column is assigned to the model
        $this->assertNotNull($model->id);
        $this->assertNotSame(0, $model->id);

        // Select afterwards
        $oStatement = $this->dataObject->pdo->prepare('SELECT * FROM user');

        $this->assertTrue($oStatement->execute());
        $this->assertSame(['id' => $id, 'last_name' => 'Doe', 'first_name' => 'John'], $oStatement->fetch(PDO::FETCH_ASSOC));

        $model->firstName = 'Jane';
        $model->lastName  = 'Smith';

        // No exception thrown
        $model->save();

        $this->assertSame(State::PERSISTENT, $model->state);

        // The AutoIncrement column is not changed
        $this->assertSame($id, $model->id);

        // Select afterwards
        $oStatement = $this->dataObject->pdo->prepare('SELECT * FROM user');

        $this->assertTrue($oStatement->execute());
        $this->assertSame(['id' => $model->id, 'last_name' => 'Smith', 'first_name' => 'Jane'], $oStatement->fetch(PDO::FETCH_ASSOC));

        $model->delete();

        // Select afterwards
        $oStatement = $this->dataObject->pdo->prepare('SELECT * FROM user');

        $this->assertTrue($oStatement->execute());
        $this->assertNull($oStatement->fetch(PDO::FETCH_ASSOC));
        $this->assertSame(0, $oStatement->rowCount());

        $this->assertSame(State::DETACHED, $model->state);
    }

    /** Returns a working DataObject to the mysql database */
    private function getConnectionClass(): Mysql
    {
        return new Mysql('percona', 'root', 'root-password', ['dbname' => 'model']);
    }
}

class User extends Model
{
    public string $table = 'user';

    #[PrimaryKey]
    #[Column(Type::INTEGER)]
    #[AutoIncrement]
    public ?int $id = null;

    #[Column(Type::VARCHAR, 'last_name')]
    public ?string $lastName = null;

    #[Column(Type::VARCHAR, 'first_name')]
    #[Required]
    public ?string $firstName = null;
}